Repository vk-cs/terraform-provider-vkcs, pull requests merged in 2023-12, with the labels that each got.

#338 refactor lb examples
  examples/keymanager/secret/certificate.pem
  examples/keymanager/secret/private-key.key
  examples/lb/base.tf
  examples/lb/listener/base-loadbalancer.tf
  examples/lb/listener/base-networking.tf
  examples/lb/listener/https/base-container.tf
  examples/lb/listener/https/base-key.tf
  examples/lb/listener/https/base-loadbalancer.tf
  examples/lb/listener/https/base-networking.tf
  examples/lb/listener/https/base-secret-cert.tf
  examples/lb/listener/https/certificate.pem
  examples/lb/listener/https/main.tf
  examples/lb/listener/https/private-key.key
  examples/lb/listener/main.tf
  examples/lb/loadbalancer/base-networking.tf
  examples/lb/loadbalancer/main-datasource.tf
  examples/lb/loadbalancer/main.tf
  examples/lb/main.tf
  examples/lb/member/base-listener.tf
  examples/lb/member/base-loadbalancer.tf
  examples/lb/member/base-networking.tf
  examples/lb/member/base-pool.tf
  examples/lb/member/main.tf
  examples/lb/members/base-computes.tf
  examples/lb/members/base-firewall.tf
  examples/lb/members/base-flavor.tf
  examples/lb/members/base-image.tf
  examples/lb/members/base-listener.tf
  examples/lb/members/base-loadbalancer.tf
  examples/lb/members/base-networking.tf
  examples/lb/members/base-pool.tf
  examples/lb/members/main.tf
  examples/lb/monitor/base-listener.tf
  examples/lb/monitor/base-loadbalancer.tf
  examples/lb/monitor/base-networking.tf
  examples/lb/monitor/base-pool.tf
  examples/lb/monitor/main.tf
  examples/lb/pool/base-listener.tf
  examples/lb/pool/base-loadbalancer.tf
  examples/lb/pool/base-networking.tf
  examples/lb/pool/main.tf
  templates/lb/data-sources/vkcs_lb_loadbalancer.md.tmpl
  templates/lb/data-sources/vkcs_lb_loadbalancer/main.tf
  templates/lb/resources/vkcs_lb_listener.md.tmpl
  templates/lb/resources/vkcs_lb_listener/main.tf
  templates/lb/resources/vkcs_lb_loadbalancer/main.tf
  templates/lb/resources/vkcs_lb_member/main.tf
  templates/lb/resources/vkcs_lb_members/main.tf
  templates/lb/resources/vkcs_lb_monitor/main.tf
  templates/lb/resources/vkcs_lb_pool/main.tf
Labels: documentation

#371 interface_attach_resource
  examples/compute/interface_attach/base-firewall.tf
  examples/compute/interface_attach/base-image.tf
  examples/compute/interface_attach/base-instance.tf
  examples/compute/interface_attach/base-networking.tf
  examples/compute/interface_attach/base-port.tf
  examples/compute/interface_attach/main-network.tf
  examples/compute/interface_attach/main.tf
  templates/compute/resources/vkcs_compute_interface_attach.md.tmpl
  templates/compute/resources/vkcs_compute_interface_attach/basic/main.tf
  templates/compute/resources/vkcs_compute_interface_attach/existing_port/main.tf
  templates/compute/resources/vkcs_compute_interface_attach/fixed_ip/main.tf
  templates/compute/resources/vkcs_compute_interface_attach/multiple_interfaces/main.tf
  templates/compute/resources/vkcs_compute_interface_attach/multiple_interfaces_ordered/main.tf
Labels: documentation

#375 vpnaas resources
  examples/vpnaas/endpoint_group/main.tf
  examples/vpnaas/endpoint_group/subnet/base-networking.tf
  examples/vpnaas/endpoint_group/subnet/main.tf
  examples/vpnaas/ike_policy/main.tf
  examples/vpnaas/ipsec_policy/main.tf
  examples/vpnaas/service/base-networking.tf
  examples/vpnaas/service/main.tf
  examples/vpnaas/site_connection/base-endpoints.tf
  examples/vpnaas/site_connection/base-ike-policy.tf
  examples/vpnaas/site_connection/base-ipsec-policy.tf
  examples/vpnaas/site_connection/base-networking.tf
  examples/vpnaas/site_connection/base-service.tf
  examples/vpnaas/site_connection/base-subnet-edpoints.tf
  examples/vpnaas/site_connection/base.tf
  examples/vpnaas/site_connection/main.tf
  templates/vpnaas/resources/vkcs_vpnaas_endpoint_group.md.tmpl
  templates/vpnaas/resources/vkcs_vpnaas_endpoint_group/main.tf
  templates/vpnaas/resources/vkcs_vpnaas_ike_policy/main.tf
  templates/vpnaas/resources/vkcs_vpnaas_ipsec_policy/main.tf
  templates/vpnaas/resources/vkcs_vpnaas_service/main.tf
  templates/vpnaas/resources/vkcs_vpnaas_site_connection.md.tmpl
  templates/vpnaas/resources/vkcs_vpnaas_site_connection/import.sh
Labels: documentation

#381 Use chart name as addon's default name
  CHANGELOG.md
  vkcs/kubernetes/resource_addon.go
Labels: service/kubernetes

#384 Release v0.6.0
  .release/provider-schema.json
  CHANGELOG.md
  vkcs/internal/providerwrapper/schema_base.go
Labels: release

#368 resource_rule_policy
  examples/lb/l7policy/base-listener.tf
  examples/lb/l7policy/base-loadbalancer.tf
  examples/lb/l7policy/base-networking.tf
  examples/lb/l7policy/base-pool.tf
  examples/lb/l7policy/main.tf
  examples/lb/l7rule/base-listener.tf
  examples/lb/l7rule/base-loadbalancer.tf
  examples/lb/l7rule/base-networking.tf
  examples/lb/l7rule/base-policy.tf
  examples/lb/l7rule/base-pool.tf
  examples/lb/l7rule/main.tf
  templates/lb/resources/vkcs_lb_l7policy/main.tf
  templates/lb/resources/vkcs_lb_l7rule/main.tf
Labels: documentation

#383 resources_snetwork_security
  examples/sharedfilesystem/base.tf
  examples/sharedfilesystem/main.tf
  examples/sharedfilesystem/securityservice/main.tf
  examples/sharedfilesystem/share/base-networking.tf
  examples/sharedfilesystem/share/base-sharenetwork.tf
  examples/sharedfilesystem/share/main-datasource.tf
  examples/sharedfilesystem/share/main.tf
  examples/sharedfilesystem/share_access/base-networking.tf
  examples/sharedfilesystem/share_access/base-share.tf
  examples/sharedfilesystem/share_access/base-sharenetwork.tf
  examples/sharedfilesystem/share_access/main.tf
  examples/sharedfilesystem/sharenetwork/base-networking.tf
  examples/sharedfilesystem/sharenetwork/main-datasource.tf
  examples/sharedfilesystem/sharenetwork/main.tf
  templates/sharedfilesystem/data-sources/vkcs_sharedfilesystem_share.md.tmpl
  templates/sharedfilesystem/data-sources/vkcs_sharedfilesystem_share/main.tf
  templates/sharedfilesystem/data-sources/vkcs_sharedfilesystem_sharenetwork.md.tmpl
  templates/sharedfilesystem/data-sources/vkcs_sharedfilesystem_sharenetwork/main.tf
  templates/sharedfilesystem/resources/vkcs_sharedfilesystem_securityservice/main.tf
  templates/sharedfilesystem/resources/vkcs_sharedfilesystem_share/main.tf
  templates/sharedfilesystem/resources/vkcs_sharedfilesystem_share_access/nfs/main.tf
  templates/sharedfilesystem/resources/vkcs_sharedfilesystem_sharenetwork/main.tf
Labels: documentation

#389 refactor db examples
  examples/db/backup/base-config.tf
  examples/db/backup/base-firewall.tf
  examples/db/backup/base-flavor.tf
  examples/db/backup/base-instance.tf
  examples/db/backup/base-networking.tf
  examples/db/backup/base.tf
  examples/db/backup/main.tf
  examples/db/cluster/base-flavor.tf
  examples/db/cluster/base-networking.tf
  examples/db/cluster/base.tf
  examples/db/cluster/main.tf
  examples/db/config_group/base.tf
  examples/db/config_group/main.tf
  examples/db/database/base-config.tf
  examples/db/database/base-firewall.tf
  examples/db/database/base-flavor.tf
  examples/db/database/base-instance.tf
  examples/db/database/base-networking.tf
  examples/db/database/base.tf
  examples/db/database/main.tf
  examples/db/instance/base-config.tf
  examples/db/instance/main.tf
  examples/db/user/base-config.tf
  examples/db/user/base-database.tf
  examples/db/user/base-firewall.tf
  examples/db/user/base-flavor.tf
  examples/db/user/base-instance.tf
  examples/db/user/base-networking.tf
  examples/db/user/base.tf
  examples/db/user/main.tf
  templates/db/resources/vkcs_db_backup.md.tmpl
  templates/db/resources/vkcs_db_backup/import.sh
  templates/db/resources/vkcs_db_cluster.md.tmpl
  templates/db/resources/vkcs_db_cluster/import.sh
  templates/db/resources/vkcs_db_cluster_with_shards.md.tmpl
  templates/db/resources/vkcs_db_cluster_with_shards/import.sh
  templates/db/resources/vkcs_db_config_group.md.tmpl
  templates/db/resources/vkcs_db_config_group/import.sh
  templates/db/resources/vkcs_db_database.md.tmpl
  templates/db/resources/vkcs_db_database/import.sh
  templates/db/resources/vkcs_db_instance.md.tmpl
  templates/db/resources/vkcs_db_instance/import.sh
  templates/db/resources/vkcs_db_user.md.tmpl
  templates/db/resources/vkcs_db_user/import.sh
Labels: documentation
