Repository vk-cs/terraform-provider-vkcs, pull requests merged in 2023-11, with the labels that each got.

#332 Fix user agent header
  CHANGELOG.md
  vkcs/internal/clients/config.go
Labels: bugfix

#330 Fix tests and examples for VPNaaS
  CHANGELOG.md
  examples/vpnaas/site_connection/main.tf
  vkcs/vpnaas/resource_endpoint_group.go
  vkcs/vpnaas/resource_service.go
  vkcs/vpnaas/resource_site_connection.go
Labels: bugfix, service/vpn

#334 Add RetryFunc for all resources and datasources
  CHANGELOG.md
  vkcs/internal/clients/config.go
  vkcs/internal/util/errutil/err.go
Labels: enhancement

#337 Add "skip_deletion" option for vkcs_db_user
  CHANGELOG.md
  vkcs/db/data_source_user_test.go
  vkcs/db/import_user_test.go
  vkcs/db/resource_user.go
  vkcs/db/resource_user_test.go
Labels: enhancement, service/db

#333 resource keymanager_secret
  examples/keymanager/container/base-key.tf
  examples/keymanager/container/base-secret-cert.tf
  examples/keymanager/container/certificate.pem
  examples/keymanager/container/main-datasource.tf
  examples/keymanager/container/main.tf
  examples/keymanager/container/private-key.key
  examples/keymanager/secret/certificate.pem
  examples/keymanager/secret/main-cert.tf
  examples/keymanager/secret/main-datasource.tf
  examples/keymanager/secret/main.tf
  examples/keymanager/secret/private-key.key
  templates/keymanager/data-sources/vkcs_keymanager_container.md.tmpl
  templates/keymanager/data-sources/vkcs_keymanager_container/main.tf
  templates/keymanager/data-sources/vkcs_keymanager_secret.md.tmpl
  templates/keymanager/data-sources/vkcs_keymanager_secret/main.tf
  templates/keymanager/resources/vkcs_keymanager_container.md.tmpl
  templates/keymanager/resources/vkcs_keymanager_container/acl/main.tf
  templates/keymanager/resources/vkcs_keymanager_container/main.tf
  templates/keymanager/resources/vkcs_keymanager_secret.md.tmpl
  templates/keymanager/resources/vkcs_keymanager_secret/acl/main.tf
  templates/keymanager/resources/vkcs_keymanager_secret/expiration/main.tf
  templates/keymanager/resources/vkcs_keymanager_secret/main.tf
  templates/keymanager/resources/vkcs_keymanager_secret/whitespaces/main.tf
Labels: documentation
